version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::792348923773:role/service-role/flask-cd-codebuild-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - python3 -m virtualenv ~/.venv
      - source ~/.venv/bin/activate
      - make install
      - make lint

  build:
    commands:
      - make deploy